mongodb:
  image: ebuildy/mongodb
  volumes:
    - /kinoulink/api-infra/docker/mongodb/config:/var/config:ro
    - /var/kinoulink/mongodb/data:/var/data:rw
  ports:
    - 27017:27017
  environment:
    - SERVICE_NAME=mongodb
    - SERVICE_TAGS=mongodb,data

web:
  build: web
  volumes:
    - /kinoulink/api-infra/docker/web/config:/var/config:ro
    - /var/kinoulink/web/log/nginx:/var/log/nginx:rw
  ports:
    - 80:80
  links:
    - mongodb
  environment:
    - SERVICE_NAME=web
    - SERVICE_TAGS=nginx,php,app

consul:
  command: -server -bootstrap -ui-dir /ui
  image: progrium/consul:latest
  ports:
    - "8300"
    - "8400"
    - "8500"
    - "8600/udp"
  environment:
    - "affinity:container!=nodes_consul_*"
    - SERVICE_TAGS=admin,data
  net: "host"

registrator:
  command: consul://127.0.0.1:8500
  image: progrium/registrator:latest
  volumes:
  - "/var/run/docker.sock:/tmp/docker.sock"
  environment:
  - "affinity:container!=nodes_registrator_*"
  net: "host"

