mongodb:
  image: ebuildy/mongodb
  volumes:
    - /kinoulink/api-infra/docker/mongodb/config:/var/config:ro
    - /var/kinoulink/mongodb/data:/var/data:rw
  ports:
    - 27017:27017

web:
  build: web/docker
  volumes:
    - /kinoulink/api-infra/docker/web/config:/var/config:ro
    - /kinoulink/api:/var/www:rw
    - /var/kinoulink/web/log/nginx:/var/log/nginx:rw
  ports:
    - 80:80
  links:
    - mongodb
