mongodb:
  image: ebuildy/mongodb
  volumes:
    - /kinoulink/api-infra/docker/mongodb/config:/var/config:ro
    - /var/kinoulink/mongodb/data:/var/data:rw
  ports:
    - 27017:27017

web:
  build: web/docker
  volumes:
    - /kinoulink/api-infra/docker/web/config:/var/config:ro
    - /kinoulink/api:/var/www:rw
    - /var/kinoulink/web/log/nginx:/var/log/nginx:rw
  ports:
    - 80:80
  links:
    - mongodb

consul:
  command: -server -bootstrap -ui-dir /ui
  image: progrium/consul:latest
  ports:
  - "8300"
  - "8400"
  - "8500"
  - "8600/udp"
  environment:
  - "affinity:container!=nodes_consul_*"
  net: "host"

registrator:
  command: consul://127.0.0.1:8500
  image: progrium/registrator:latest
  volumes:
  - "/var/run/docker.sock:/tmp/docker.sock"
  environment:
  - "affinity:container!=nodes_registrator_*"
  net: "host"

