Vagrant.configure("2") do |config|

    if ARGV[1] == 'azure'
        ARGV.delete_at(1)
        deployOnAzure = true
    else
        deployOnAzure = false
    end

    config.vm.provider :virtualbox do |v|
        v.name = "Kinoulink Consul"
        #v.customize [
        #    "modifyvm", :id,
        #    "--name", "Pmm",
        #    "--memory", 1024,
        #    "--natdnshostresolver1", "on",
        #    "--cpus", 1,
        #]
    end

    config.vm.box = "hashicorp/precise64"

    config.vm.network :private_network, ip: "192.168.56.11"

    #############################################################
    # Ansible provisioning (you need to have ansible installed)
    #############################################################

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
        #ansible.verbose = "vvvv"
        #ansible.inventory_path = "../inventories/dev"
        ansible.limit = 'all'
        ansible.extra_vars = {
            private_interface: "192.168.56.11",
            hostname: "Kinoulink Consul"
        }
    end

    config.vm.synced_folder "../../", "/var/kinoulink/infra", type: "nfs", mount_options: ["tcp"]
end